apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advertise
  template:
    metadata:
      labels:
        app: advertise
    spec:
      containers:
      - name: advertise
        image: advertise:2
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: advertise
spec:
  selector:
    app: advertise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000

